volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env.example
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: never52/kittygram_backend:latest
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      cp -r /app/collected_static/. /backend_static/static/ &&
      python manage.py migrate &&
      gunicorn kittygram_backend.wsgi:application --bind 0.0.0.0:8000
      "
    env_file: .env.example
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  frontend:
    image: never52/kittygram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    env_file: .env.example
    volumes:
      - static:/frontend_static
  gateway:
    image: never52/kittygram_gateway:latest
    env_file: .env.example
    volumes:
      - static:/staticfiles
      - media:/media
    ports:
      - 9000:80
    depends_on:
      - backend
